### ISSUE TITLE
How do I load the latest version into BC?

### ISSUE THREAD

**Issue by quadfin** [Microsoft/cal-open-library#110]
The latest rev of COL contains codeunits not present in the latest available release of BC -- e.g., COD30XX.txt (XX > 27).  I am trying to prepare a submission to the COL but I need to develop against the latest COL version.  I pulled the latest BC on-prem image (13.0.24623) and the latest BC docker image (13.0.24630.25789) neither of which contain the latest COL.  I am not able to import the .txt files due to license / object range restrictions.
How should I proceed?
(please don't say wait until next month)
Thanks in advance.

**Comment by JesperSchulz** [comment]
It is correct, that you will not find the latest open library codeunits in the released version of BC. The library is based on the upcoming (now spring) release of BC and you will hence only find the objects in the developer preview docker images. Now that you mention it, that might actually not be the best development model for contributions due to the mentioned license restrictions! What happens is you grab the latest developer preview? Can you complete your development there, or do you run into the same blockers?
Another solution would of course be to open the license for the new codeunits already now, which would unblock you. However, we're currently looking into alternative solutions to the .NET wrappers, which is why I'm hesitant to take this step right now. Please try with the developer preview and let me know how that went! Thanks!

**Comment by quadfin** [comment]
Can you post a link for the developer preview?  I can't find it on docker hub.  (can only find bcsandbox)
Another (not optimal approach) might be to make available a .fob with skeletal versions of the codeunits in the library.  Then we could import that .fob and overwrite with the .txt from the library.
Is there any public info on the alternate approach that you mention?
Thanks.

**Comment by JesperSchulz** [comment]
Developer previews are obtainable through our Ready to Go program (http://aka.ms/readytogo)! Here you will find the latest and greatest developments. Highly recommended :-)
I'm afraid I don't yet have any public info on alternate approaches quite yet. We're currently only spiking into those to see, if there are other ways to this.
It is new to me that branching is disabled to this repo! I need to dig into that. Worked just fine for me a couple of days ago!

**Comment by JesperSchulz** [comment]
I just tried once more on a clean machine without any problems:
![image](https://user-images.githubusercontent.com/19796701/48492010-22cd8e80-e829-11e8-8cfd-8b98be8481cb.png)
What error do you get?

**Comment by quadfin** [comment]
Not sure what happened -- something weird when I forked.
I deleted the fork and started over -- seems ok now.
I just issued a pull request for the changes.
Hope it passes.
