### ISSUE TITLE
Calling a Webservice with a Certificate

### ISSUE THREAD

**Issue by moulikaku** [microsoft/cal-open-library#114]
Im trying to recreate this c# function in BC and i'm having problem with X509Certificate2,  can you please point me in right direction?

public static void SupportPing()
        {
            
            string EndPoint = Properties.Settings.Default.SupportServicesEndPoint;

          
            WSHttpBinding binding = new WSHttpBinding();
            http://binding.Security .Mode = SecurityMode.Transport;
            http://binding.Security .Transport.ClientCredentialType = HttpClientCredentialType.Certificate;

         
            SupportServicesClient service = new SupportServicesClient(binding, new EndpointAddress(EndPoint));

          
            X509Certificate2 cert = new X509Certificate2(Properties.Settings.Default.CertificateFilePath, Properties.Settings.Default.PrivateKeyPassword, X509KeyStorageFlags.PersistKeySet);
            service.ClientCredentials.ClientCertificate.Certificate = cert;
            service.Endpoint.EndpointBehaviors.Add(new CustomMessageInspector());

         
            SupportPingRequest ping = new SupportPingRequest();
            ping.Input = "Hello World!";

         
            SupportPingResponse pingResponse = service.PingSupport(ping);

          
            Console.WriteLine(pingResponse.Output);
        }

**Comment by mortenseifert** [comment]
I am having the same issue. I assume that the certificate you load is a self signed certificate, where the subject of the subject does not match that of the service, hence the validation of the certificate fails because you cannot overload the EndpointBehaviour from AL.

I am by no means an expert in Certificate, but I see it somehow related to https://github.com/Microsoft/AL/issues/2758; however my understanding is it just solves the class used by the AL wrapper 
`Great! I think that proves that the problem is that AL wrapper uses `X509Certificate` instead of `X509Certificate2`.`

**Comment by JesperSchulz** [comment]
Sorry, this issue got lost. If you're still having that problem, try posting your question to the following resources instead, as we cannot offer support through this forum: 

[Business Central Community](https://community.dynamics.com/business/f/758)
[mibuso forum](https://forum.mibuso.com/categories/nav-three-tier)
[Dynamics User Group](https://dynamicsuser.net/nav/f/developers)
