### ISSUE TITLE
Codeunit 706 - Zip Stream Wrapper Encoding

### ISSUE THREAD

**Issue by amulaj** [microsoft/cal-open-library#120]
The Zip Stream Wrapper Codeunit should be extended with a Encoding Parameter. 
If the Zip content includes file names with special characters then you cant store the file name correctly. 

To be able to use e specific codepage the OpenZipFromStream Function could look something like that: 
variable gSystemTextEncoding = System.Text.Encoding.'mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089'

Code: 
OpenZipFromStream(pInputStream : InStream;pZipArchiveModeIsUpdate : Boolean;pCodePageNumber : Integer)
CLEAR(gZipTempBlob);
gZipTempBlob.Blob.CREATEOUTSTREAM(OutputStream);
COPYSTREAM(OutputStream,pInputStream);

IF pZipArchiveModeIsUpdate THEN
  gZipArchive := gZipArchive.ZipArchive(OutputStream,gZipArchiveMode.Update,FALSE,gSystemTextEncoding.GetEncoding(pCodePageNumber))
ELSE
  gZipArchive := gZipArchive.ZipArchive(OutputStream,gZipArchiveMode.Read,FALSE,gSystemTextEncoding.GetEncoding(pCodePageNumber));

**Comment by JesperSchulz** [comment]
Info: Seems related to: https://github.com/microsoft/ALAppExtensions/issues/1173.

**Comment by JesperSchulz** [comment]
We've just completed our work on our Compression Management module, which I will publish to GitHub very soon. If it does not address your needs, we may have to tweak that module. However, the module is not going to be made available to BC before our fall 19 release. Is that an issue? If so, we will have to backport a solution, which we will have to break again coming fall 19.

**Comment by dcenic** [comment]
We support 4 binary data encodings in Business Central AL - MsDos, Windows, UTF8 and UTF16. Is it good enough that we add an extra parameter of AL type TextEncoding (so you get support for these four encodings), or do you need ability to make a ZipArchive with any given encoding?
If you need the latter, keep in mind that the method that saves the zip archive to an OutStream will return an OutStream that is in the encoding that is not supported within Business Central.

**Comment by niku-live** [comment]
I would like to give my comment about encoding, as somehow it is incorrectly assumed that 4 categories of encoding is enough. As I come from country where 4 basic encodings are not enough at all I see NAV/BC encoding support as broken and in our add-ons we usually need to fallback to .NET Encoding object to overcome this limitation (and for on-premise deployments it is good enough solutions).

It is normal for one client to use Windows-1252 encoding as their own, while others use Windows-1257, Windows-1253 and so on. No imagine that I need to import CSV file saved in Windows-1251 encoding while originally my regional settings says that my Windows encoding is Windows-1252. Using standard functionality application treats file as Windows-1252 and all non-Latin characters are completely incorrect. Since database internally uses UTF encoding if I can somehow read CSV file correctly (by doing that in .NET for example) in the end I get correct data and everything else works correctly. 

The same can be said about ZipArchive functionality as well. It is completely normal to get an archive from client where file names in this archive are in different encoding than my Windows encoding. So what should be done in this situation - explaining client how to fix his archive file is not the solution as generally speaking archive isn't incorrect, so we fallback to .NET again and it works, but again we need to use custom solution in place of standard one.

So what I wanted to illustrate with my examples - maybe it is good time to think again about NAV TextEncoding implementation.  For example using codepage number as parameter in all functions where TextEncoding type currently is used and then giving developers such constants as TextEncoding.UTF8, TextEncoding.UTF16, TextEncoding.Windows, TextEncoding.MsDos which basically are just numbers indicating current codepages based on regional settings.

**Comment by amulaj** [comment]
@dcenic: 

The 4 supported data encodings are good enough for us. We actually use Codepage 850. 
You can go ahead. Thank you very much for your answer.

**Comment by dcenic** [comment]
The new method is checked in - you will be able to specify the code page number for the ZipArchive text encoding. It will be available in Zip Stream Wrapper codeunit in Business Central Update 27, which will most likely be available during August.
In the Business Central Fall 19 release, Zip Stream Wrapper codeunit is deprecated and replaced by Compression Management codeunit, and you will be able to do the same with Compression Management.

**Comment by JesperSchulz** [comment]
A new version of COD706 was checked in and pushed to this repo. It will ship in the next update. Resolving issue.
