### ISSUE TITLE
Usage in NAV2018CU2

### ISSUE THREAD

**Issue by SirBETE** [Microsoft/cal-open-library#55]
Hello

I want to make use of the functions `ConvertValueToBase64 `and `ConvertValueFromBase64` in this new COD10 Type helper, in order to get rid of dotnet-usage.

How do I do this?
Can I download the COD10.txt from the CAL-open-library, import it into NAV CSIDE and compile the object?
If I then do 'download symbols', can I make a variable of codeunit 10 and call those functions?

Kind Regards,
SirBETE

**Comment by StanislawStempin** [comment]
You can use code from this library in your on-prem installation in the same way as you would do any other base application changes. To use them in AL/new compiler you then need to follow instructions from:  https://docs.microsoft.com/en-us/dynamics-nav/developer/devenv-running-cside-and-al-side-by-side

For further help, please reach out through regular support channels since this GitHub repo and AL repo are focused on supporting the latest pre-release version of the product.

**Comment by JesperSchulz** [comment]
I hope that answered your questions. In case you're having problems or further questions, please reopen this issue :-) Happy side-by-side coding!
